"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.loginController = exports.getByIdUserController = exports.getAllController = exports.createUserController = exports.loginUseCase = exports.getByIdUserUseCase = exports.getAllUseCase = exports.createUserUseCase = exports.mysqlReactionsRepository = void 0;
const MysqlUsersRepository_1 = require("./MysqlUsersRepository");
const CreateUserUseCase_1 = require("../application/CreateUserUseCase");
const GetByIdUserUseCase_1 = require("../application/GetByIdUserUseCase");
const GetAllUseCase_1 = require("../application/GetAllUseCase");
const LoginUseCase_1 = require("../application/LoginUseCase");
const CreateUserController_1 = require("./controllers/CreateUserController");
const GetAllController_1 = require("./controllers/GetAllController");
const GetByIdReactionController_1 = require("./controllers/GetByIdReactionController");
const LoginController_1 = require("./controllers/LoginController");
exports.mysqlReactionsRepository = new MysqlUsersRepository_1.MysqlUsersRepository();
exports.createUserUseCase = new CreateUserUseCase_1.CreateUserUseCase(exports.mysqlReactionsRepository);
exports.getAllUseCase = new GetAllUseCase_1.GetAllUseCase(exports.mysqlReactionsRepository);
exports.getByIdUserUseCase = new GetByIdUserUseCase_1.GetByIdPorcentajeUseCase(exports.mysqlReactionsRepository);
exports.loginUseCase = new LoginUseCase_1.LoginUseCase(exports.mysqlReactionsRepository);
exports.createUserController = new CreateUserController_1.CreateReactionController(exports.createUserUseCase);
exports.getAllController = new GetAllController_1.GetAllController(exports.getAllUseCase);
exports.getByIdUserController = new GetByIdReactionController_1.GetByIdReactionController(exports.getByIdUserUseCase);
exports.loginController = new LoginController_1.LoginController(exports.loginUseCase);
