"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getByIdDesviacionController = exports.getAllController = exports.createDesviacionController = exports.getByIdDesviacionUseCase = exports.getAllDesviacionUseCase = exports.createDesviacionUseCase = exports.mysqlDesviacionRepository = void 0;
const MysqlDesviacionRepository_1 = require("./MysqlDesviacionRepository");
const CreateDesviacionUseCase_1 = require("../application/CreateDesviacionUseCase");
const GetByIdDesviacionUseCase_1 = require("../application/GetByIdDesviacionUseCase");
const GetAllUseCase_1 = require("../application/GetAllUseCase");
const CreateDesviacionController_1 = require("./controllers/CreateDesviacionController");
const GetAllController_1 = require("./controllers/GetAllController");
const GetByIdDesviacionController_1 = require("./controllers/GetByIdDesviacionController");
const MysqlReactionsRepository_1 = require("../../Reactions/infrastructure/MysqlReactionsRepository");
const MysqlExpeRepository_1 = require("../../Media/infrastructure/MysqlExpeRepository");
exports.mysqlDesviacionRepository = new MysqlDesviacionRepository_1.MysqlDesviacionRepository();
const mysqlReactionsRepo = new MysqlReactionsRepository_1.MysqlReactionsRepository();
const mysqlMediaRepo = new MysqlExpeRepository_1.MysqlMediaRepository();
exports.createDesviacionUseCase = new CreateDesviacionUseCase_1.CreateDesviacionUseCase(exports.mysqlDesviacionRepository);
exports.getAllDesviacionUseCase = new GetAllUseCase_1.GetAllUseCase(exports.mysqlDesviacionRepository);
exports.getByIdDesviacionUseCase = new GetByIdDesviacionUseCase_1.GetByIdDesviacionUseCase(exports.mysqlDesviacionRepository);
exports.createDesviacionController = new CreateDesviacionController_1.CreateDesviacionController(exports.createDesviacionUseCase, mysqlReactionsRepo, mysqlMediaRepo);
exports.getAllController = new GetAllController_1.GetAllController(exports.getAllDesviacionUseCase, exports.createDesviacionController);
exports.getByIdDesviacionController = new GetByIdDesviacionController_1.GetByIdDesviacionController(exports.getByIdDesviacionUseCase);
