"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getByIdMediaController = exports.getAllController = exports.createMediaController = exports.getByIdMediaUseCase = exports.getAllMediaUseCase = exports.createMediaUseCase = exports.mysqlMediaRepository = void 0;
const MysqlExpeRepository_1 = require("./MysqlExpeRepository");
const CreateMediaUseCase_1 = require("../application/CreateMediaUseCase");
const GetByIdMediaUseCase_1 = require("../application/GetByIdMediaUseCase");
const GetAllUseCase_1 = require("../application/GetAllUseCase");
const CreateMediaController_1 = require("./controllers/CreateMediaController");
const GetAllController_1 = require("./controllers/GetAllController");
const GetByIdExpeController_1 = require("./controllers/GetByIdExpeController");
const MysqlReactionsRepository_1 = require("../../Reactions/infrastructure/MysqlReactionsRepository");
exports.mysqlMediaRepository = new MysqlExpeRepository_1.MysqlMediaRepository();
const mysqlReactionsRepo = new MysqlReactionsRepository_1.MysqlReactionsRepository();
exports.createMediaUseCase = new CreateMediaUseCase_1.CreateMediaUseCase(exports.mysqlMediaRepository);
exports.getAllMediaUseCase = new GetAllUseCase_1.GetAllUseCase(exports.mysqlMediaRepository);
exports.getByIdMediaUseCase = new GetByIdMediaUseCase_1.GetByIdMediaUseCase(exports.mysqlMediaRepository);
exports.createMediaController = new CreateMediaController_1.CreateMediaController(exports.createMediaUseCase, mysqlReactionsRepo);
exports.getAllController = new GetAllController_1.GetAllController(exports.getAllMediaUseCase, exports.createMediaController);
exports.getByIdMediaController = new GetByIdExpeController_1.GetByIdExpeController(exports.getByIdMediaUseCase);
